import type { Metadata } from "next";
import { RequestServiceProvider } from "@/components/request-service";
import { rootFontVariables } from "./fonts";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${rootFontVariables} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <RequestServiceProvider>{children}</RequestServiceProvider>
      </body>
    </html>
  );
}
