import type { Metadata } from "next";
import { SectionEntrance } from "@/components/primitives/SectionEntrance";
import { TextWipeLines } from "@/components/primitives/TextWipeLines";
import { RequestServiceProvider } from "@/components/request-service";
import { rootFontVariables } from "./fonts";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${rootFontVariables} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        {/* Renders nothing. One observer for every section frame on the page -
            see `SectionEntrance`, and `buildRootLayout` in site-export.ts,
            which mounts the same component into an exported site. */}
        <SectionEntrance />
        {/* Renders nothing, and loads its splitter only on a page that carries
            a Text wipe section - see `TextWipeLines`. */}
        <TextWipeLines />
        <RequestServiceProvider>{children}</RequestServiceProvider>
      </body>
    </html>
  );
}
